### PR TITLE
Switch from full lodash to lodash.map

### LINKED ISSUE #5: Switch from lodash to lodash.map?
It looks like we're importing all of [**lodash**](https://www.npmjs.com/package/lodash) and only using one method; `_.map()`. We can probably just switch to [**lodash.map** module](https://www.npmjs.com/package/lodash.map) and save a few KB.

In fact, it looks like our dependencies would shrink from about 2.1M to 224K.

``` sh
$ du -hs ./node_modules/lodash
2.1M    ./node_modules/lodash

$ du -hs ./node_modules/lodash.map
224K    ./node_modules/lodash.map
```

### PR DESCRIPTION
**Pull request by pdehaan**
Fixes #5

### CODE REVIEW

**Comment by vladikoff** [comment]
YESSSS

**Comment by pdehaan** [comment]
On that note, not sure if we can just switch to the native `Array.map()` and save that last 224K and skip lodash completely, but hey...

**Comment by vladikoff** [comment]
@pdehaan also see https://github.com/ajoslin/conventional-changelog/search?utf8=%E2%9C%93&q=lodash

**Comment by pdehaan** [comment]
But hey, at least our current `npm i --production` modules are ~384K (versus the 10.0M they were before). :shipit:

**Comment by pdehaan** [comment]
Oh interesting. The **conventional-changelog** is probably using the full lodash since they're using the following:
- `_.map()`
- `_.assign()` (/index.js)
- `_.merge()` (/index.js)
- `_.omit()` (/cli.js)
- `_.isUndefined()` (/cli.js)

**Pull request merged**
